site_name: "Docs Hellman Alert"
site_author: hellman.team
site_url: https://docs.alert.hellman.team
copyright: '© 2020 Hellman'
repo_name: HellmanResearch/userhandbook
repo_url: https://github.com/HellmanResearch/userhandbook
theme:
  name: material
  favicon: './images/favicon_hellman.ico'
  logo: './images/logo.png'
  font:
    text: 'Open Sans'
extra_css:
  - 'stylesheets/extra.css'
markdown_extensions:
  - codehilite
  - admonition
  - attr_list
  - toc:
      permalink: true
nav:
  - Introduction: index.md
  - Metrics: metrics.md
  - Subscriptions: subscriptions.md
  - Triggered: triggered.md
  - API: api.md
  - Feedback: feedback.md
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/HellmanResearch
    - icon: fontawesome/brands/github-alt
      link: https://github.com/HellmanResearch